### ISSUE TITLE
[DATABASE] DB 설계

### ISSUE THREAD

**Issue by seoyeon0918** [junhuihi/jigu-cam#10]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능추가 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 기능추가 개요

디비 설계

## TODO

- [ ] DB 코드 추가
