### ISSUE TITLE
[FEATURE] 이미지검색->이미지 가져오기 프론트

### ISSUE THREAD

**Issue by stella9921** [junhuihi/jigu-cam#2]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 기능추가 개요

이미지 검색 메뉴에서 이미지 가져오기 기능 추가

## TODO

- [x] 이미지 가져오기 버튼과 기능 추가 
- [x] 이미지 인식 오류 버튼 만들고 imgError 함수와 연결
