### ISSUE TITLE
[FEATURE] 홈 화면 슬라이드 기능 수정

### ISSUE THREAD

**Issue by romdyfo** [junhuihi/jigu-cam#5]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능추가 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 기능추가 개요

홈 화면 슬라이드 기능 수정 

## TODO

- [x] 슬라이드 배경 이미지 지정
- [x] 각 슬라이드 별 디자인 수정
