### ISSUE TITLE
[FEATURE] 이미지 검색->카메라로 찍기 기능추가

### ISSUE THREAD

**Issue by seoyeon0918** [junhuihi/jigu-cam#8]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능추가 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 기능추가 개요

이미지 검색 메뉴에서 이미지 카메라로 찍기 눌렀을 때 카메라로 연결

## TODO

- [ ] 카메라 버튼 css 만들기
- [ ] take a photo 함수 작성
- [ ] 찍은 사진 데이터베이스에 저장
- [ ] 찍은 사진 화면에 렌더링하기
