### ISSUE TITLE
[FEATURE] 객체인식 기능 안드로이드 연동

### ISSUE THREAD

**Issue by seoyeon0918** [junhuihi/jigu-cam#9]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능추가 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 기능추가 개요

yolov5 기반 객체인식 카메라 기능

## TODO

- [ ] yolov5 에서 app 내용을 깃허브주소로 변경
- [ ] assets에 model training에서 학습한 파일 저장
